In [1]:
#Social_Network_Ads.csv

**Importing the libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

**Importing the dataset**

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')

In [4]:
df.shape

(400, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

**Splitting the dataset into the Training set and Test set**

**Feature Scaling**

In [8]:
from sklearn.preprocessing import OneHotEncoder

df['Gender']=df['Gender'].astype('category')
df['gender']=df['Gender'].cat.codes

In [9]:
df = df.drop(columns=['User ID','Gender'])

In [10]:
column = df.pop('Purchased')

In [11]:
df.insert(3, 'Purchased', column)

In [12]:
df.head()


Age  EstimatedSalary  gender  Purchased
0   19            19000       1          0
1   35            20000       1          0
2   26            43000       0          0
3   27            57000       0          0
4   19            76000       1          0

In [13]:
df.isnull().sum()

Age                0
EstimatedSalary    0
gender             0
Purchased          0
dtype: int64

In [14]:
x = df.iloc[:,0:3]
x

Age  EstimatedSalary  gender
0     19            19000       1
1     35            20000       1
2     26            43000       0
3     27            57000       0
4     19            76000       1
..   ...              ...     ...
395   46            41000       0
396   51            23000       1
397   50            20000       0
398   36            33000       1
399   49            36000       0

[400 rows x 3 columns]

In [15]:
y = df.iloc[:,3]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

**Fitting Decision Tree Classification to the Training set**

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20,random_state = 8)

In [17]:
from sklearn.preprocessing import StandardScaler 
func = StandardScaler()
func.fit(x_train)
x_train = func.transform(x_train)
x_test = func.transform(x_test)

print(f'shape of x_train : {x_train.shape}')
print(f'shape of y_train : {y_train.shape}')
print(f'shape of x_test : {x_test.shape}')
print(f'shape of y_test : {y_test.shape}')

shape of x_train : (320, 3)
shape of y_train : (320,)
shape of x_test : (80, 3)
shape of y_test : (80,)


In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score,KFold


model = RandomForestClassifier(criterion = 'entropy')

kfold = KFold(n_splits = 5)
scores = cross_val_score(model,x,y,cv = kfold)


print(f'The cross validation scores for DecisionTreeClassifier model is:{scores}',end = '\n\n')
print(f'The mean of cross_val_scores:{scores.mean()}',end = '\n\n')

model.fit(x_train,y_train)

print(f'Train score:{format(model.score(x_train,y_train))}',end = '\n\n')
print(f'Test score:{format(model.score(x_test,y_test))}',end = '\n\n')

The cross validation scores for DecisionTreeClassifier model is:[0.8625 0.9375 0.8125 0.7875 0.7875]

The mean of cross_val_scores:0.8375

Train score:1.0

Test score:0.9



**Predicting the Test set results**

In [23]:
preds_tr = model.predict(x_train)
preds_tr

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,

In [24]:
preds_te = model.predict(x_test)
preds_te

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

**Making the Confusion Matrix**

In [25]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score

print("Accuracy of DecisionTreeClassifier model is: ",accuracy_score(y_test,preds_te))
print("DecisionTreeClassifier model Classification report: ","\n",classification_report(y_test,preds_te))
print("Confusion matrix for DecisionTreeClassifier model:","\n",confusion_matrix(y_test,preds_te))

Accuracy of DecisionTreeClassifier model is:  0.9
DecisionTreeClassifier model Classification report:  
               precision    recall  f1-score   support

           0       0.93      0.93      0.93        54
           1       0.85      0.85      0.85        26

    accuracy                           0.90        80
   macro avg       0.89      0.89      0.89        80
weighted avg       0.90      0.90      0.90        80

Confusion matrix for DecisionTreeClassifier model: 
 [[50  4]
 [ 4 22]]


**Visualising the Training set results**

**Visualising the Test set results**